import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import TopNav from "~/_components/topnav";

export const metadata: Metadata = {
  title: "Theo Practice",
  description: "Generated by devbayel by watching tutorial",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className={`flex flex-col gap-4 p-5`}>
        <div className="w-full">
          <TopNav/>
        </div>

        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
